name: Dart
on:
  push:
    branches: 
      - main
    paths:
      - lib/**/*.dart
      - test/**/*.dart
      - .github/workflows/dart.yml
jobs:
  build:
    name: Neo Pubspec Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        sdk:
          - stable
          - beta
          - dev
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
